# Generated by Django 4.1.5 on 2023-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rok',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='film',
            name='tytul',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
