# Generated by Django 4.1.5 on 2023-03-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0003_film_imdb_rating_film_okladka_film_opis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkowInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (1, 'Akcji'), (3, 'Sci-fi'), (2, 'Historyczny')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmy.dodatkowinf'),
        ),
    ]
