# Generated by Django 4.1.5 on 2023-03-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0004_dodatkowinf_film_dodatkowe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkowinf',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Historyczny'), (1, 'Akcji')], default=0),
        ),
        migrations.CreateModel(
            name='ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kometaz', models.TextField(blank=True, default='')),
                ('gwiazki', models.PositiveSmallIntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmy.film')),
            ],
        ),
    ]
