# Generated by Django 4.1.5 on 2023-03-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0005_alter_dodatkowinf_gatunek_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkowinf',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Inne'), (2, 'Historyczny'), (1, 'Akcji')], default=0),
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='Filmy.film')),
            ],
        ),
    ]
