# Generated by Django 4.1.5 on 2023-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0006_alter_dodatkowinf_gatunek_rezyser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkowinf',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Historyczny'), (1, 'Akcji')], default=0),
        ),
    ]
